Added step and linear bdry interpolation methods
polyfem/polyfem pull request #129
Opened 2022-10-07 16:32 UTC by Pranav-Jain

2022-10-07 20:38 UTC, zfergus commented on src/polyfem/assembler/GenericProblem.hpp
> +		class PiecewiseConstantInterpolation : public Interpolation
These are all pretty much the same class with a different eval function. I suggest creating a parent class 
```c++
class PiecewiseInterpolation : public Interpolation
{
		public:
			void init(const json &params) override;

		private:
			std::vector<double> points_;
			std::vector<double> values_;
			int extend_ = -1; //0-constant, 1-extrapolate, 2-repeat, 3-repeat_offset
			double offset_ = 0.0;
}
```
and then inherit from this class and override eval.

2022-10-07 20:38 UTC, zfergus commented on src/polyfem/assembler/GenericProblem.hpp
> +			int extend_ = -1; //0-constant, 1-extrapolate, 2-repeat, 3-repeat_offset
Make this an `enum`

2022-10-07 20:38 UTC, zfergus commented on src/polyfem/assembler/GenericProblem.cpp
> +				extend_ = -1;
Does FEBio define a default? We should use that same one. or else throw and error here.

2022-10-07 20:49 UTC, zfergus commented on src/polyfem/assembler/GenericProblem.cpp
> +			if (t < points_[0])
I think the extend applies in this case too.

2022-10-07 20:49 UTC, zfergus commented on src/polyfem/assembler/GenericProblem.cpp
> +			if (extend_ == 0)
This is the same between all `PiecewiseInterpolation` classes, right? If so move it into a function in the `PiecewiseInterpolation` parent class and call that one in the child class when needed.

2022-10-07 20:49 UTC, zfergus commented on src/polyfem/assembler/GenericProblem.cpp
> +					if (t-points_[points_.size()-1] >= points_[i] && t-points_[points_.size()-1] < points_[i+1]) {
For this just make it a (recursive) call to `eval(fmod(t, points[-1]) + points[0])+offset`.

2022-10-07 20:53 UTC, zfergus commented on src/polyfem/assembler/GenericProblem.hpp
> +			double offset_ = 0.0;
I think `offset_` should just be `values_[-1]`

2022-10-07 20:55 UTC, zfergus commented on src/polyfem/assembler/GenericProblem.cpp
> +				extend_ = -1;
Default is constant in FEBio: https://help.febio.org/FebioUser/FEBio_um_3-4-Subsection-3.17.1.html

2022-10-09 15:52 UTC, teseoch commented on src/polyfem/assembler/GenericProblem.cpp
> +			if (t < points_[0])
This should go, right?

2022-10-09 15:53 UTC, teseoch commented on src/polyfem/assembler/GenericProblem.cpp
> +				throw "Points must be an array";
There is a function log and throw, cna you use that?

2022-10-09 15:54 UTC, teseoch reviewed
2 small things

2022-10-09 20:27 UTC, zfergus requested changes

2022-10-09 20:27 UTC, zfergus commented on src/polyfem/assembler/GenericProblem.cpp
> +			extend(t);
Shouldnt you return this?

2022-10-09 20:27 UTC, zfergus commented on src/polyfem/assembler/GenericProblem.cpp
> +					ext_ = repeat_offset;
Else throw error?

2022-10-09 20:38 UTC, Pranav-Jain commented on src/polyfem/assembler/GenericProblem.cpp
> +			extend(t);
Yes. Good catch. Thanks!

2022-10-10 00:19 UTC, zfergus approved these changes

2022-10-10 06:36 UTC, merged